services:
  ovva:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${SHINY_PORT:-3838}:${SHINY_PORT:-3838}"
      - "${VIDEO_SERVER_PORT:-8888}:${VIDEO_SERVER_PORT:-8888}"
    volumes:
      - ${DATA_PATH:-../../../data}:/data
      - ${VIDEO_PATH:-../../../videos}:/videos:ro
    environment:
      SHINY_HOST: ${SHINY_HOST:-0.0.0.0}
      SHINY_PORT: ${SHINY_PORT:-3838}
      DATA_PATH: /data
      VIDEO_SERVER: ${VIDEO_SERVER:-lighttpd}
      VIDEO_SERVER_PORT: ${VIDEO_SERVER_PORT:-8888}
      ALT_VIDEO_PATH: /videos
